server.port = 8082
# spring.application.name=aiService

# database connection
spring.data.mongodb.uri=mongodb://localhost:27017/fitnessActivity

# The address of your Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Optional: Helps Eureka identify the instance faster
eureka.instance.prefer-ip-address=true

rabbitmq.exchange.name = fitness.exchange
rabbitmq.queue.name = activity.queue
rabbitmq.routing.key = activity.tracking

rabbitmq.host: localhost
rabbitmq.port: 5672
rabbitmq.username: guest
rabbitmq.password: guest

gemini.api.key=${GEMINI_API_KEY}

logging.level.org.springframework.cloud.gateway=TRACE

