spring.application.name=eureka
server.port=8761

# 2. Tell the app NOT to register itself as a client
eureka.client.register-with-eureka=false

# 3. Tell the app NOT to pull the list of services from others
eureka.client.fetch-registry=false
